version: '2'

services:
  redis-sgx:
    image: enclaive/redis-sgx
    container_name: "redis-sgx"
    build:
      context: .
    devices:
      - "/dev/sgx_enclave:/dev/sgx_enclave"
  redis:
    image: enclaive/redis-sgx
    container_name: "redis"
    entrypoint: ""
    build:
      context: .
