version: '2'

services:
  redis:
    image: enclaive/redis-sgx
    container_name: "redis-sgx"
    build:
      context: .
    volumes:
      - /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket
    ports:
      - "6379:6379"
    devices:
      - "/dev/sgx_enclave:/dev/sgx_enclave"
